# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCriaCadastroIsaac():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criaCadastroIsaac(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1366, 720)
    self.driver.find_element(By.CSS_SELECTOR, ".user-message").click()
    self.driver.find_element(By.ID, "login-form-email").click()
    self.driver.find_element(By.ID, "login-form-email").send_keys("isaacsamuelsilva@msds.com.br")
    self.driver.find_element(By.ID, "login-btn-toggle").click()
    self.driver.find_element(By.ID, "registration-form-fname").click()
    self.driver.find_element(By.ID, "registration-form-fname").send_keys("Isaac Samuel")
    self.driver.find_element(By.ID, "registration-form-lname").click()
    self.driver.find_element(By.ID, "registration-form-lname").send_keys("Silva")
    self.driver.find_element(By.ID, "registration-form-bdate").click()
    self.driver.find_element(By.ID, "registration-form-bdate").send_keys("07/04/1991")
    self.driver.find_element(By.ID, "registration-form-gender").click()
    dropdown = self.driver.find_element(By.ID, "registration-form-gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Masculino']").click()
    self.driver.find_element(By.ID, "male").click()
    self.driver.find_element(By.ID, "registration-form-cpf").click()
    self.driver.find_element(By.ID, "registration-form-cpf").send_keys("696.812.519-62")
    self.driver.find_element(By.ID, "registration-form-phone").click()
    self.driver.find_element(By.ID, "registration-form-phone").send_keys("+554425684552")
    self.driver.find_element(By.ID, "registration-form-email-confirm").click()
    self.driver.find_element(By.ID, "registration-form-email-confirm").send_keys("isaacsamuelsilva@msds.com.br")
    self.driver.find_element(By.ID, "registration-form-password").click()
    self.driver.find_element(By.ID, "registration-form-password").send_keys("JqgPjqCpSQ")
    self.driver.find_element(By.ID, "registration-form-password-confirm").click()
    self.driver.find_element(By.ID, "registration-form-password-confirm").send_keys("JqgPjqCpSQ")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-control-label").click()
  
