# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestModaCacauShow():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_modaCacauShow(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1366, 720)
    element = self.driver.find_element(By.CSS_SELECTOR, "#cat_005 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#cat_005 > span").click()
    self.driver.execute_script("window.scrollTo(0,463)")
    self.driver.find_element(By.LINK_TEXT, "Tênis Pampili Chocomonstros Tween Vermelho").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".it__minicart .minicart-quantity").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-menu-text:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,6)")
    self.driver.find_element(By.CSS_SELECTOR, ".clear-cart-btn").click()
    self.driver.find_element(By.LINK_TEXT, "SIM").click()
  
