# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCompraProduto():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_compraProduto(self):
    self.driver.get("https://www.cacaushow.com.br/")
    self.driver.set_window_size(1366, 720)
    element = self.driver.find_element(By.ID, "cat_005")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "cat_003")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > a > .tag-popular > span").click()
    element = self.driver.find_element(By.ID, "cat_003")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Caixa de Bombons Mini Show laCreme ao Leite 108g").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-add-to-cart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".it__minicart .minicart-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".clear-cart-btn").click()
    self.driver.find_element(By.LINK_TEXT, "SIM").click()
    self.driver.execute_script("window.scrollTo(0,328)")
  
